travis:
  secure:
    BINSTAR_TOKEN: 0q0tA44FmagBAcXuXmdJZTdf8oOBCIOPCGpzHG2NXidz/TcAjUMjTR3Ii2iaBER6IS3+EtBwc8pt7Y7LnzJN0R8ES4T0npqTZh5wfCMNyrMCVlUfV4lI6O8rJtFbmKvGR5CJs2rvQHacONt64MvFLecZbn9Z0nThu/1u/NusmDVdtCSqbN6rjR7uaU1WoGBKNsdpkFNQRIY4bCmmrS1iAaK/Ze2WO7V/P3YOaej/Qe+Og3ziRaZv/ehwaFWUNn6Uq/YOwqQkez5/xVsYK5YKb7aySNTip8qDamu1pUG9DOSB8j2mPxPMN/yiAFX0p1/+IKj1Ik6fsCtC7B/THcGXKCjFtbav31dlIVHUEOzVEWxpVogwBz1GCxbH7YEze8B3g69oP+P77dbgBoTBNuwUSI3jhKGActFZR+ybgBUrgxFXda3xy/8JrGNxLeBFHHaelyHw9pLkNlGSnlL0PsTxHMgodZ88f83Bb4oqy4Wyvv2IYvzswyn+OxS/ey0n4UOk/Eu2gPhVijQmySaz4BYQ5kDZmGoeV1i2dCg/uTCobJnUOQaEGI3ftCsLKnNNlnfE5VinsnaYFwAG5VEqyRsJ4Od5DPOXI86fKXvhHSralRGSu4qW7OCWJXb3qPVBMpIO9EMm457rxwRNDvWU5GEeqOWEbM5dL1abIzMs5LclpFo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
